settings.dynamic = true

[bits.155]
flow = 0.3
name = "Guitar up"
rotate.bone = "upper_arm_l"
rotate.target.z = -15

[bits.156]
flow = 1.0
name = "Head left"
rotate.bone = "head"
rotate.target.y = 15

[bits.157]
flow = 1.0
name = "Head right"
rotate.bone = "head"
rotate.target.y = -15

[bits.158]
flow = 0.7
name = "Head up"
rotate.bone = "head"
rotate.target.x = 15

[bits.161]
flow = 0.2
name = "Right arm up"
rotate.bone = "upper_arm_r"
rotate.target.z = 10

[bits.165]
flow = 0.8
name = "Body"
anim.id = "body_tilt"

[bits.166]
flow = 1.7
name = "Mouth"
rotate.bone = "jaw"
rotate.target.x = -25
